packages:
  - "replace-act-import"
  - "replace-use-form-state"
  - "use-context-hook"
  - "update-react-imports"
  - "replace-reactdom-render"
  - "replace-string-ref"
  - "rename-unsafe-lifecycles"
  - "manual-bind-to-arrow"
  - "sort-comp"
  - "pure-render-mixin"
  - "react-proptypes-to-prop-types"
  - "error-boundaries"
  - "find-dom-node"
